id: A69DBAFFC
title: f87E0
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.658475
  last_modified_at: 2022-05-27 14:50:10.658477
