id: A69DBAFFC
title: f9199
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.659913
  last_modified_at: 2022-05-27 14:50:10.659915
