id: A69DBAFFC
title: f852E
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.657834
  last_modified_at: 2022-05-27 14:50:10.657837
