id: A69DBAFFC
title: f4442
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.638527
  last_modified_at: 2022-05-27 14:50:10.638533
