id: A69DBAFFC
title: fE01A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.750315
  last_modified_at: 2022-05-27 14:50:10.750318
