id: A69DBAFFC
title: f92C5
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.661492
  last_modified_at: 2022-05-27 14:50:10.661495
