id: A69DBAFFC
title: f094F
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:50:10.624378
  last_modified_at: 2022-05-27 14:50:10.624385
